// Everything the site says about the projects lives here.
// Screenshots are in img/shots/<id>/ (made by tools/images.py); `play` points at an arcade cabinet.

export const PROFILE = {
  name: 'Sethy Pagna UNG',
  short: 'Pagna',
  email: 'ungsethypagna@gmail.com',
  linkedin: 'https://www.linkedin.com/in/sethy-pagna-ung-833ab8283/',
  github: 'https://github.com/SethyPagna',
};

// status colours map onto the palette tokens in site.css
export const CATEGORIES = [
  { id: 'all', label: 'All projects' },
  { id: 'software', label: 'Software' },
  { id: 'ai', label: 'AI apps' },
  { id: 'games', label: 'Games' },
  { id: 'team', label: 'Team & course' },
];

const gh = repo => `https://github.com/SethyPagna/${repo}`;

export const PROJECTS = [
  {
    id: 'business-os', code: 'BOS', no: '01', name: 'Business OS', color: 'volt', featured: true,
    cats: ['software'], kicker: 'Retail software', year: '2026',
    status: { label: 'Live · in service', color: 'acid' },
    tagline: 'A connected workspace for retail.',
    summary: 'Point of sale, inventory, branch transfers, shifts and reporting, plus a customer storefront, in English and Khmer.',
    about: 'Business OS runs a real cosmetics shop in Cambodia. The same Cloudflare Worker serves the owner and cashier back office and the public storefront, and every screen works in English and Khmer.',
    features: [
      'Point of sale with barcode and camera scanning, held orders and shift controls',
      'Offline-first PWA: sales queue in IndexedDB and sync when the connection returns',
      'Shop and warehouse inventory with transfers, FIFO batches and stock-in sessions',
      'Sales hub with amendments, returns, fees, reports and exports',
      'Public storefront with brand rail, filters, promotions and a live-preview editor',
      'Thermal receipts and QR codes, real-time sync across devices, audit log with undo',
      'About 6,100 translated strings in both English and Khmer',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Cloudflare Workers', 'D1', 'R2', 'Durable Objects', 'Hono'],
    note: 'In production for Leang Beauty. The admin screenshots use the repository’s test fixtures, so product names are synthetic.',
    links: [
      { label: 'Visit storefront', href: 'https://leangbeauty.com', kind: 'live' },
      { label: 'Source', href: gh('business-os'), kind: 'code' },
    ],
    route: 'Retail POS + storefront, EN/KH', gate: 'CLOUDFLARE',
  },
  {
    id: 'learn', code: 'LRN', no: '02', name: 'LEARN', color: 'cyan', featured: true,
    cats: ['ai', 'software'], kicker: 'AI · EdTech', year: '2026',
    status: { label: 'Active development', color: 'cyan' },
    tagline: 'Capture → create → practise → review.',
    summary: 'Notes, docs, sheets and slides beside AI tutoring, quizzes, vocabulary practice and progress tracking.',
    about: 'A personal study studio. Material you write in the studio becomes practice: the AI tutor can coach, quiz, make flashcards or translate, and the practice modes track what you keep getting wrong.',
    features: [
      'Studio for notes, docs, sheets (CSV export) and slides (PPTX export)',
      'AI tutor modes: coach, rewrite, quiz, flashcards, translate and mistake review',
      'Practice: quizzes, timed sprints, flashcards, matching and review cards',
      'Study rooms, group chat with calls, and study battles over Durable Objects',
      'Knowledge vault, graph, calendar planner and a file library on R2',
      '18 interface languages, including Khmer, Chinese and Arabic (RTL)',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'TipTap', 'Cloudflare D1 · R2 · DO'],
    note: 'Features vary in readiness. The demo accounts are listed on the login page.',
    links: [
      { label: 'Open app', href: 'https://learn-ten-pearl.vercel.app', kind: 'live' },
      { label: 'Cloudflare mirror', href: 'https://learn.learn-app.workers.dev', kind: 'live' },
      { label: 'Source', href: gh('LEARN'), kind: 'code' },
    ],
    route: 'Notes → AI tutor → quizzes', gate: 'NEXT.JS',
  },
  {
    id: 'allchess', code: 'ACH', no: '03', name: 'AllChess', color: 'acid', featured: true,
    cats: ['games', 'software'], kicker: 'Games · Web', year: '2026', play: 'allchess',
    status: { label: 'Playable · Sep 2026', color: 'acid' },
    tagline: 'Discover how the world plays chess.',
    summary: 'A game studio for 21 board games, from Xiangqi, Shogi and Ouk Chaktrang (Khmer chess) to draughts and Jungle, on physical 3D tabletops with bots that run in the browser.',
    about: 'Play first, learn as you go. The September 2026 arcade build turns AllChess into a game studio: a visual library of 21 board games, each with a physical 3D tabletop and its own custom piece collections. Its own rules engine covers every game, and the bots run in your browser: Stockfish 18 for chess, a custom search for everything else.',
    features: [
      'Game studio: a visual library of 21 games with search by native names, favourites and launch modes (bot, local, friend, quick match, watch)',
      'Physical 3D tabletops for every family: Western, Khmer, Shogi with hand stands and 3D drops, Xiangqi, Janggi, Makruk, draughts with stacked kings, Konane, Jungle…',
      'Piece collections: marble chess, Celadon Xiangqi, carved Shogi, Courtyard and Atelier Ouk Chaktrang, Club and Rosette draughts, Shore Konane',
      'Board style picker per game: collection, 2D style (artwork, clear, letters), board colours',
      'Bots from beginner to 4000 Elo; Stockfish 18 WASM for chess, a custom search for the other games',
      'Factual move review, undo/redo, local saves with import/export, 19 languages',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'three.js', 'Stockfish WASM', 'Cloudflare D1 · DO'],
    note: 'The arcade runs the 29 September 2026 Shore checkpoint entirely in your browser: bot and pass-and-play for all 21 games, with the latest committed bot fixes, mobile controls and studio lighting. Online matches, rooms and accounts are in the online app, which runs an older build.',
    links: [
      { label: 'Play in the arcade', href: '#arcade/allchess', kind: 'play' },
      { label: 'Online app (older build)', href: 'https://allchess.learn-app.workers.dev', kind: 'live' },
      { label: 'Arcade source', href: 'https://github.com/SethyPagna/AllChess/tree/8940655e558c8834cd8c8f0f37f7d493222d4d8f', kind: 'code' },
    ],
    route: 'Chess variants of the world', gate: 'NEXT + D1',
  },
  {
    id: 'urcut', code: 'URC', no: '04', name: 'UrCut + UrVoice', color: 'magenta', featured: true,
    cats: ['ai'], kicker: 'AI · Creative', year: '2026', private: true,
    status: { label: 'Desktop web preview', color: 'magenta' },
    tagline: 'Your cut. Visual, fast, private.',
    summary: 'A local-first video editor you can try in a desktop browser: import media, edit a timeline and export MP4/WebM on your device. UrVoice adds speech tools in the local app.',
    about: 'UrCut runs in the browser and keeps your media on your device: no account, no upload. UrVoice is its companion engine, an OpenAI-style speech API on localhost for transcription, 132 preset voices and consent-gated Khmer voice cloning.',
    features: [
      'Icon-first editor: media, voice, text, stickers, effects and captions panels',
      'Auto captions with in-browser Whisper, plus SRT/ASS import and Khmer line wrapping',
      'AI voiceover takes dropped at the playhead with instant captions using local UrCut and UrVoice',
      'Local Khmer, English and Chinese speech engine (UrVoice, Python/FastAPI)',
      'Exports MP4/WebM in the browser and marks AI voices in the file metadata',
      'Seven bundled fonts, six of them Khmer, so text works offline',
    ],
    stack: ['Next.js', 'TypeScript', 'Rust/WASM (wgpu)', 'Python', 'faster-whisper', 'ONNX'],
    note: 'Desktop preview: media stays in this browser; export files to keep your finished edits. AI voice generation and cloning need local UrCut with UrVoice. Online sound search is unavailable; captions may download a speech model. Built on OpenCut classic (MIT), with private source.',
    credit: { label: 'OpenCut classic (MIT)', href: 'https://github.com/OpenCut-app/opencut-classic' },
    links: [{ label: 'Open desktop web preview', href: 'https://urcut-preview.ungsethypagna.workers.dev', kind: 'live' }],
    route: 'Browser editor + local voice', gate: 'NEXT + PY',
  },
  {
    id: 'codeage', code: 'CDA', no: '05', name: 'CodeAge', color: 'violet', featured: true,
    cats: ['ai'], kicker: 'AI · Dev tools', year: '2026', private: true,
    status: { label: 'Alpha · private', color: 'violet' },
    tagline: 'AI conversations beside your code.',
    summary: 'A Windows workbench with chat and code panels, editor, terminals and Git diffs, using local Ollama models or API providers.',
    about: 'A local-first workbench for agents, projects and history. Up to nine chat and terminal panels sit next to a Monaco editor, with approval modes that decide what an agent may do on your machine.',
    features: [
      'Adaptive grid of up to nine chat and real terminal panels',
      'Code view with Monaco editor, file tree and diffs',
      'Built-in agents: builder, reviewer, researcher, debugger and planner',
      'Access modes (ask, approve, full, read-only) with an approvals inbox',
      'Encrypted local store (AES-256-GCM) with backups',
      'Assistant with voice and a 3D presence; scheduled routines',
    ],
    stack: ['Electron', 'React 19', 'TypeScript', 'Express', 'SQLite', 'Monaco', 'xterm'],
    note: 'Windows local alpha (0.7.9). No public download yet.',
    links: [],
    route: 'AI workbench beside your code', gate: 'ELECTRON',
  },
  {
    id: 'edsync', code: 'EDS', no: '06', name: 'EdSync', color: 'blue', featured: true,
    cats: ['software', 'ai'], kicker: 'EdTech', year: '2026',
    status: { label: 'Preview', color: 'blue' },
    tagline: 'Connect classroom work across roles.',
    summary: 'Separate student, teacher and admin spaces for lessons, classes, assignments, gradebooks and progress.',
    about: 'EdSync is a role-based learning workspace. Teachers build lessons with an AI lesson creator and a canvas studio, students work through classes and practice, and admins run portals for organisations.',
    features: [
      'AI lesson creator: slide lessons with Socratic questions and an exit ticket',
      'Course studio on a Fabric.js canvas with PPTX export',
      'Ten practice modes, from quizzes and exams to sprints and mistake retry',
      'Teacher gradebook, grading, analytics, planner and discussions',
      'Organisation portals with join codes and an admin console',
      'Nine languages, eight themes, compact role navigation and offline sync',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'Fabric.js', 'Cloudflare D1 · R2 · Vectorize'],
    note: 'The latest public preview runs on Cloudflare. Classroom content is still being built; checkout is manual and email-provider setup remains in progress. The gallery shows an earlier preview.',
    links: [
      { label: 'Open app', href: 'https://edsync.learn-app.workers.dev', kind: 'live' },
      { label: 'Source', href: gh('EdSync'), kind: 'code' },
    ],
    route: 'Classes for students & teachers', gate: 'NEXT.JS',
  },
  {
    id: 'living-kingdom', code: 'LKG', no: '07', name: 'Living Kingdom', color: 'lime', game: true,
    cats: ['games'], kicker: 'Game · Unreal Engine 5 + browser', year: '2026', private: true, play: 'living-kingdom',
    status: { label: 'Playable · browser edition', color: 'volt' },
    tagline: 'A sandbox kingdom RPG in the making, now in the browser too.',
    summary: 'An Unreal Engine 5.8 C++ prototype: combat, chopping and carrying, a realm gate to a second area, a Founder with procedural animation, and saves. The browser edition ports both maps and the First Hearth quest line to three.js.',
    about: 'You are a founder with a small, protected Origin Space that is meant to grow into a home, market or capital. The UE5 build has two maps, physics props, falling trees, navmesh enemies with telegraphed attacks, a warden fight and a collect–repair–recruit–build loop. The browser edition is a TypeScript port of that playtest: the floating Origin and the Stonebrook valley laid out from the same authoring scripts, the journey ledger, economy and combat numbers copied from the C++, and the real founder and kit meshes. The UE5 build stays the reference.',
    features: [
      'About 50 native C++ gameplay classes (combat, carry, choppable trees, journey economy)',
      'Procedural animation: lean, breathing, look-at, foot IK, hands on carried items',
      '24-hour day cycle driving sun, fog and lamps; shared wind for grass and lanterns',
      'Tab hub with map, satchel, a Founder page with coat and hair dyes, and rebindable controls',
      'Versioned saves with migration, packaged Windows builds and automation tests',
      'Browser edition: both maps, the First Hearth quest line, tree felling, carrying, veil shades and the warden fight, with Rapier physics',
    ],
    stack: ['Unreal Engine 5.8', 'C++', 'Blueprints', 'Blender', 'TypeScript', 'three.js', 'Rapier'],
    note: 'Built with AI agents under my direction. The browser edition is made for keyboard and mouse; touch screens get an on-screen stick and buttons.',
    links: [{ label: 'Play the browser edition', href: '#arcade/living-kingdom', kind: 'play' }],
    route: 'Fantasy world, UE5 prototype', gate: 'UE5 C++',
  },
  {
    id: 'sandline', code: 'SND', no: '08', name: 'Sandline', color: 'orange', game: true,
    cats: ['games'], kicker: 'Game · Unreal Engine 5 + browser', year: '2026', private: true, play: 'sandline',
    status: { label: 'Playable · browser edition', color: 'orange' },
    tagline: 'A tactical shooter against bots, now in the browser too.',
    summary: 'A UE 5.8 shooter with 19 modes on six generated maps, bots with vision and reaction delay, a buy economy and a battle royale. The browser edition ports the same rules, maps and art to three.js.',
    about: 'Sandline is built in Unreal Engine 5 and played offline against bots; online multiplayer is not built yet. The browser edition is a TypeScript port of the UE C++ gameplay: the same six maps parsed from the generated map data, the full weapon table and economy, the four bot skill tiers, and the real Blender agents, guns and props with the synthesised audio. The UE5 v0.2.x build stays the reference.',
    features: [
      '19 modes: competitive defusal, wingman, deathmatch, arms race, war, domination, hardpoint, retakes and a battle royale',
      'Six maps designed in Python and built at runtime, from Sirocco to a 128×128 island, lit at noon, overcast, golden hour or sunset',
      'Bots with a vision cone, line of sight, reaction delay, aim drift, team buy plans and A* navigation',
      '34 guns, knives and six grenade types with spray patterns, penetration, armour and a CS-style money economy',
      'Blender-generated agents, first-person arms with two-bone IK, guns and props; Python-synthesised audio',
      'Browser edition: UE-style HUD, radar, buy menu, scoreboard and match summary; 35 tests including headless bot matches',
    ],
    stack: ['Unreal Engine 5.8', 'C++', 'Blueprints', 'Python', 'Blender', 'TypeScript', 'three.js'],
    note: 'Built with AI agents under my direction. The browser edition is desktop only (WebGL 2, keyboard and mouse).',
    links: [{ label: 'Play the browser edition', href: '#arcade/sandline', kind: 'play' }],
    route: 'Offline bot shooter, UE5', gate: 'UE5 C++',
  },
  {
    id: 'wreckabulary', code: 'WRK', no: '09', name: 'Wreckabulary', color: 'violet', game: true,
    cats: ['games', 'team'], kicker: 'Game · Team · COMP4122', year: '2026',
    status: { label: 'Team project', color: 'violet' },
    tagline: 'Wreck the room, build the word!',
    summary: 'A 2–4 player couch party game in Unity 6: smash furniture into its letters, then spell weapons, walls and wings.',
    about: 'Everything is made of letter tiles. Smash → scavenge → spell → summon: carry up to six letters, open the word wheel and summon a SHIELD, SPRING or a swarm of BEES. Versus, co-op “Moving Day” and a tutorial are in; the art is still placeholder blocks.',
    features: [
      'Destruction that bursts objects into the exact letters of their name',
      'Real-time word solver over the letters you carry',
      'Drop-in joining for up to four gamepads or two players on one keyboard',
      'Versus “Dibs!” (letters are your health) and co-op “Moving Day”',
      'Ragdoll roommates with a wobbly rig; pooled physics letter tiles',
    ],
    stack: ['Unity 6', 'C#', 'URP', 'Input System'],
    note: 'Key art and the gameplay image are the team’s concept mock-ups; in-game art is still placeholder.',
    links: [
      { label: 'Source', href: gh('wreckabulary'), kind: 'code' },
      { label: 'Team repo', href: 'https://github.com/cchayadap/wreckabulary', kind: 'code' },
    ],
  },
  {
    id: 'omnidrama', code: 'OMD', no: '10', name: 'OmniDrama', color: 'blue',
    cats: ['software'], kicker: 'Media · Local app', year: '2026', private: true,
    status: { label: 'New · private', color: 'orange' },
    tagline: 'Your shows in one local library.',
    summary: 'A Windows video library: searchable catalogue, episode player with saved progress, and a studio that converts uploads with FFmpeg.',
    about: 'A local library for one administrator: import episodes, and FFmpeg validates and converts them for the browser player. Publishing waits until rights are declared and every episode is present.',
    features: [
      'Discover page with featured series, genres and production-type filters',
      'Episode browser with filters, six sort orders and watch state',
      'Player with seeking, speed, auto-next, saved position and shortcuts',
      'Durable import jobs with FFmpeg transcoding and posters',
      'Scheduled feed scans that respect robots.txt, plus a review inbox',
      'Strict CSP, same-origin and SSRF guards; runs only on localhost',
    ],
    stack: ['React 19', 'TypeScript', 'Express 5', 'SQLite', 'FFmpeg', 'Vite'],
    note: 'Ships with an original sample series only; not a public streaming service.',
    links: [],
    route: 'Local video library + player', gate: 'NODE + TS',
  },
  {
    id: 'khshop', code: 'KHS', no: '11', name: 'KhShop', color: 'magenta',
    cats: ['software'], kicker: 'Marketplace prototype', year: '2026', private: true,
    availability: 'prototype · under development',
    status: { label: 'Prototype · in development', color: 'magenta' },
    tagline: 'Shopping designed around Khmer.',
    summary: 'A Khmer-first marketplace with buyer, seller and staff workspaces: shops, listings, orders, offers and viewing appointments.',
    about: 'Khmer by default with an English switch, prices in both US dollars and riel, and search that understands Khmer text. Buyers browse and order, sellers manage their shops, and staff handle moderation and disputes. The latest source is still being tested and hardened for release.',
    features: [
      'Khmer-aware search normalisation with multi-term ranking',
      'USD/KHR display from a live rate with a fallback',
      'Shops, cart, orders, offers, viewing appointments and chat',
      'Seller workspace for listings, stock, customers and shop settings',
      'Staff queues for moderation, disputes and manual credit top-ups',
      'On-device visual search experiment (CLIP in a Web Worker)',
    ],
    stack: ['React 19', 'vinext', 'TypeScript', 'Drizzle', 'Cloudflare Workers · D1'],
    note: 'Under active hardening. The gallery shows the earlier pilot with fictional shops. Payment flows use cash or manual transfers directly to shops.',
    links: [],
  },
  {
    id: 'jarvis', code: 'JRV', no: '12', name: 'Secretary Jarvis', color: 'cyan',
    cats: ['ai'], kicker: 'AI · Desktop', year: '2026',
    status: { label: 'Prototype', color: 'cyan' },
    tagline: 'A desktop home for an AI assistant.',
    summary: 'An Electron shell around a Python backend: chat, voice, a terminal, local-model control and live stats on one home screen.',
    about: 'Jarvis wraps an agent in a desktop app: a 3D orb, assistant stream, terminal and voice on one screen, with local runtimes (llama.cpp, vLLM, Ollama) and swappable “souls”.',
    features: [
      'Home screen with 3D orb, assistant stream, terminal and live stats',
      'Local model runtimes with priority fallback, or API providers',
      'Voice in and out: Kokoro TTS, faster-whisper or whisper.cpp',
      'Hot-swappable identity and voice profiles',
      'Skills hub, plugins, MCP and a cron scheduler',
      'Seven themes and 16 interface languages',
    ],
    stack: ['Electron', 'React 19', 'TypeScript', 'Python', 'FastAPI', 'three.js'],
    note: 'Built on the open-source Hermes Agent by Nous Research (MIT).',
    credit: { label: 'Hermes Agent by Nous Research (MIT)', href: 'https://github.com/NousResearch/hermes-agent' },
    links: [{ label: 'Source', href: gh('Secretary-Jarvis'), kind: 'code' }],
  },
  {
    id: 'cargo-twin', code: 'CGT', no: '13', name: 'Cargo Twin', color: 'acid',
    cats: ['team', 'software'], kicker: 'Transport · Packing studio', year: '2026', play: 'cargo-twin',
    status: { label: 'Cargo studio · v3', color: 'acid' },
    tagline: 'Smart packing. Any space.',
    summary: 'A visual cargo-planning studio for road, sea, air, rail and custom spaces. Enter box dimensions, weights and handling rules, compare calculated layouts and watch the load plan take shape in 3D.',
    about: 'Cargo Twin grew from our team\'s AInnovator hackathon prototype (Nov 2025). Version 3 broadens it into a customizable packing studio: choose a vehicle or define its usable space with dimensions and reserved room, add mixed cargo, and compare layouts that respect support, weight and fragility. The earlier aircraft planner and physics experiments remain available in their own workspace.',
    features: [
      'Road, sea, air, rail and custom spaces with editable dimensions, payload, clearance and an excluded reserved section',
      'Cargo dimensions, quantities, per-piece weight, priority, fragility, upright orientation and maximum load on top',
      'Max fill, Balanced and Gentle strategies with non-overlap, full base support, payload and cumulative stacking-load constraints',
      'Usable-volume and payload percentages, mass-weighted centre of gravity, and clear reasons for cargo left out',
      'Interactive 3D cutaway, box inspection, top view and loading-sequence replay; editable desktop and phone layouts',
      'Save/import/export scenarios locally; retained aircraft workspace with ULD contours, physics stress tests and freighter planning',
    ],
    stack: ['React 19', 'TypeScript', 'three.js', 'cannon-es', 'Web Workers', 'Vite'],
    note: 'Illustrative planning prototype. Strategies compare feasible heuristic layouts; the replay is not a vehicle-dynamics or collision-free loading certification. Presets are editable, representative data.',
    links: [
      { label: 'Play in the arcade', href: '#arcade/cargo-twin', kind: 'play' },
      { label: 'Cargo Twin source', href: gh('cargo-twin/tree/f7c91908b50d2ccc248ee0dd410d08a80014075c/cargo-twin'), kind: 'code' },
      { label: 'v1 (hackathon)', href: 'https://ainnovator-cathay-cargotwin.figma.site', kind: 'archive' },
    ],
  },
  {
    id: 'ai-summary', code: 'AIS', no: '14', name: 'AI Summary', color: 'orange',
    cats: ['ai'], kicker: 'AI · Document intelligence', year: '2026', play: 'ai-summary',
    status: { label: 'Rebuilt · v2', color: 'orange' },
    tagline: 'Read less. Understand more.',
    summary: 'Turns PDFs, Word files, slides and notes into a brief you can check: summaries, key phrases, answers and study cards, each linked to the exact passage it came from. Runs entirely in your browser.',
    about: 'Version 2 is a rebuild of my earlier Supabase app. Everything now runs on your device: documents are parsed in background workers, summarised with graph ranking, and questions are answered by retrieving the best passages, with a citation on every sentence. Claude is an optional upgrade with your own key: abstractive summaries and chat that still cite the source.',
    features: [
      'Import PDF, DOCX, PPTX (with speaker notes), TXT, Markdown, HTML or pasted text; every passage keeps its page, slide or section',
      'Local summaries (TL;DR, short, detailed, per section) with TextRank and MMR, key phrases, names, dates and figures',
      'Q&A by BM25 retrieval: cited sentences, a short answer for dates and numbers, and an honest "not in the text"',
      'Study tools: flashcards with spaced review, a scored quiz, key terms, a mind map and a two-document comparison',
      'Optional Claude with your own key: streamed summaries, chat, "explain like I\'m new" and study guides, with citations back to the passage',
      'Library in IndexedDB: projects, search, highlights, Markdown export, delete everything',
    ],
    stack: ['React 19', 'TypeScript', 'Vite', 'pdf.js', 'Claude API', 'IndexedDB'],
    note: 'No account and no server: files stay in your browser. Version 1 (Feb 2026, Supabase + OpenRouter) is kept in the repository.',
    links: [
      { label: 'Play in the arcade', href: '#arcade/ai-summary', kind: 'play' },
      { label: 'Open AI Summary v2', href: 'https://ai-summary.ungsethypagna.workers.dev', kind: 'live' },
      { label: 'v2 source', href: gh('ai-summary-app/tree/8a77f09c6d13e0a2e5fb0dd836e6c88f61f18c2f/web'), kind: 'code' },
    ],
  },
];

export const COURSE = [
  { name: 'Secure instant messaging', what: 'COMP3334 group project: messaging with end-to-end encryption', href: gh('Comp3334_G22_Secure-Instant-Messaging-with-End-to-End-Encryption') },
  { name: 'Information systems development', what: 'COMP3122 group project', href: gh('Comp3122_G13_Information-Systems-Development') },
  { name: 'COMP2021 project', what: 'Group course project (fork of the team repository)', href: gh('COMP2021Project') },
  { name: 'Operating systems', what: 'COMP2432 group project in C (private repository)' },
];

// Arcade cabinets: `src` is self-hosted under play/, `live` is an external embed.
export const ARCADE = [
  {
    id: 'sandline', project: 'sandline', title: 'Sandline · Browser edition', kind: 'FPS · UE5 port',
    blurb: 'Pick a mode and one of six maps, buy your loadout and play rounds against bots. It uses the same rules, weapons and agents as the UE5 build.',
    controls: 'Click to aim · WASD move · Shift walk · C crouch · Space jump · LMB fire · RMB scope · R reload · E use/defuse · B buy · Tab scores · Esc pause',
    src: 'play/sandline/', aspect: '16 / 9', desktop: true, cover: 'Firefight', size: '21 MB',
  },
  {
    id: 'living-kingdom', project: 'living-kingdom', title: 'Living Kingdom · Browser edition', kind: 'RPG · UE5 port',
    blurb: 'Start on your floating Origin, fell trees and carry the logs home, then cross the veil to Stonebrook and raise your first hearth. Veil shades wait in the outer meadow.',
    controls: 'Click to look · WASD move · Shift sprint · Space jump · E interact / pick up · LMB attack · Alt or RMB dodge · Q slash · Tab hub · Esc menu',
    src: 'play/living-kingdom/', aspect: '16 / 9', cover: 'The Origin', size: '14 MB',
  },
  {
    id: 'cargo-twin', project: 'cargo-twin', title: 'Cargo Twin', kind: 'Sim · smart packing',
    blurb: 'Customize a van, container or your own space, describe the cargo, and compare weight- and fragility-aware layouts in a 3D twin.',
    controls: 'Choose a space and cargo · compare packing strategies · drag to orbit, scroll to zoom · select a box or replay the loading sequence',
    src: 'play/cargo-twin/', aspect: '16 / 10',
  },
  {
    id: 'allchess', project: 'allchess', title: 'AllChess · Game studio', kind: 'Board · 3D tabletops',
    blurb: 'The September 2026 AllChess arcade build: pick any of 21 games, play the bot or pass-and-play, and switch to the 3D tabletop.',
    controls: 'Click or drag pieces · 3D view: drag to orbit, scroll to zoom',
    src: 'play/allchess/', aspect: '16 / 10', vw: 1280, cover: 'Classic chess', size: '3D sets load per game',
  },
  {
    id: 'ai-summary', project: 'ai-summary', title: 'AI Summary v2', kind: 'Tool · local AI',
    blurb: 'Drop in a PDF, Word file or slide deck, or try a sample: get a summary, cited answers, flashcards and a mind map, all computed in your browser.',
    controls: 'Try a sample or drop your own files · Claude is optional with your own key',
    src: 'play/ai-summary/', aspect: '16 / 10',
  },
];

export const FLIGHTS = ['business-os', 'learn', 'urcut', 'codeage', 'allchess', 'edsync', 'living-kingdom', 'sandline', 'omnidrama'];

export const TOOLBOX = [
  { title: 'Languages', color: 'cyan', items: ['TypeScript', 'JavaScript', 'Python', 'C++', 'C', 'Java', 'SQL', 'C#'] },
  { title: 'Frontend & apps', color: 'magenta', items: ['React', 'Next.js', 'Vite', 'Electron', 'Tailwind', 'TipTap', 'three.js', 'PWA'] },
  { title: 'Cloud & data', color: 'volt', items: ['Cloudflare Workers', 'D1', 'R2', 'Durable Objects', 'Hono', 'Supabase', 'SQLite', 'Express'] },
  { title: 'AI', color: 'violet', items: ['Claude', 'Codex', 'Ollama', 'Whisper', 'Local TTS', 'OpenRouter', 'AI provider APIs'] },
  { title: 'Games', color: 'acid', items: ['Unreal Engine 5', 'Blueprints', 'Unity 6', 'Blender', 'WebGL'] },
  { title: 'Also used', color: 'orange', items: ['Docker', 'PostgreSQL', 'Redis', 'DuckDB', 'Vercel', 'Git', 'pnpm', 'Bun', 'Playwright'] },
];

// which projects use a tool (for the toolbox cross-links)
export const TOOL_USES = {
  TypeScript: ['business-os', 'learn', 'allchess', 'urcut', 'codeage', 'edsync', 'omnidrama', 'khshop', 'jarvis', 'cargo-twin', 'ai-summary', 'sandline', 'living-kingdom'],
  Python: ['urcut', 'jarvis', 'sandline'],
  'C++': ['living-kingdom', 'sandline'],
  'C#': ['wreckabulary'],
  React: ['business-os', 'learn', 'allchess', 'urcut', 'codeage', 'edsync', 'omnidrama', 'khshop', 'jarvis', 'cargo-twin', 'ai-summary'],
  'Next.js': ['learn', 'allchess', 'urcut', 'edsync'],
  Vite: ['business-os', 'codeage', 'omnidrama', 'khshop', 'cargo-twin', 'ai-summary', 'sandline', 'living-kingdom'],
  Electron: ['codeage', 'jarvis'],
  TipTap: ['learn', 'edsync'],
  Tailwind: ['learn', 'edsync', 'allchess', 'urcut', 'khshop', 'business-os'],
  'three.js': ['sandline', 'living-kingdom', 'cargo-twin', 'jarvis', 'codeage', 'allchess'],
  PWA: ['business-os', 'edsync', 'khshop'],
  'Cloudflare Workers': ['business-os', 'learn', 'allchess', 'edsync', 'khshop', 'urcut', 'ai-summary'],
  D1: ['business-os', 'learn', 'allchess', 'edsync', 'khshop'],
  R2: ['business-os', 'learn', 'edsync'],
  'Durable Objects': ['business-os', 'learn', 'allchess'],
  Hono: ['business-os'],
  SQLite: ['codeage', 'omnidrama', 'khshop'],
  Express: ['codeage', 'omnidrama'],
  Whisper: ['urcut', 'jarvis'],
  'Local TTS': ['urcut', 'jarvis'],
  Ollama: ['codeage', 'jarvis'],
  Claude: ['ai-summary'],
  Supabase: ['ai-summary'],
  OpenRouter: ['ai-summary'],
  'Unreal Engine 5': ['living-kingdom', 'sandline'],
  Blueprints: ['living-kingdom', 'sandline'],
  'Unity 6': ['wreckabulary'],
  Blender: ['living-kingdom', 'sandline'],
  WebGL: ['living-kingdom', 'sandline', 'allchess', 'cargo-twin', 'jarvis', 'codeage'],
  Playwright: ['business-os', 'allchess'],
};

export const MILESTONES = [
  { date: 'FEB 2023', title: 'Monash University', sub: 'CS study · Australia', color: 'blue' },
  { date: 'JUL 2023', title: 'Joined GitHub', sub: 'hello, world', color: 'dim' },
  { date: '2024', title: 'PolyU · Hong Kong', sub: 'Computer Science', color: 'cyan' },
  { date: 'MAR 2025', title: 'Operating Systems', sub: 'group project in C', color: 'violet' },
  { date: 'AUG 2025', title: 'Student Assistant', sub: 'PolyU · Aug–Oct 2025', color: 'acid' },
  { date: 'NOV 2025', title: 'AInnovator hackathon', sub: 'Cathay Cargo Twin (team)', color: 'magenta' },
  { date: 'FEB 2026', title: 'AI Summary', sub: 'document Q&A app', color: 'orange' },
  { date: 'MAR 2026', title: 'Business OS', sub: 'retail POS begins', color: 'volt' },
  { date: 'MAY 2026', title: 'LEARN · AllChess', sub: 'EdSync · Jarvis', color: 'cyan' },
  { date: 'SEP 2026', title: 'CodeAge · UrCut', sub: 'UE5 prototypes · Wreckabulary', color: 'magenta', now: true },
  { date: 'JUL 2027', title: 'Graduation', sub: 'expected', color: 'acid', future: true },
];
