// Everything the site says about the projects lives here.
// Screenshots are in img/shots/<id>/ (made by tools/images.py); `play` points at an arcade cabinet.

export const PROFILE = {
  name: 'Sethy Pagna UNG',
  short: 'Pagna',
  email: 'ungsethypagna@gmail.com',
  linkedin: 'https://www.linkedin.com/in/sethy-pagna-ung-833ab8283/',
  github: 'https://github.com/SethyPagna',
};

// status colours map onto the palette tokens in site.css
export const CATEGORIES = [
  { id: 'all', label: 'All projects' },
  { id: 'software', label: 'Software' },
  { id: 'ai', label: 'AI apps' },
  { id: 'games', label: 'Games' },
  { id: 'team', label: 'Team & course' },
];

const gh = repo => `https://github.com/SethyPagna/${repo}`;

export const PROJECTS = [
  {
    id: 'business-os', code: 'BOS', no: '01', name: 'Business OS', color: 'volt', featured: true,
    cats: ['software'], kicker: 'Retail software', year: '2026',
    status: { label: 'Live · in service', color: 'acid' },
    tagline: 'A connected workspace for retail.',
    summary: 'Point of sale, inventory, branch transfers, shifts and reporting, plus a customer storefront, in English and Khmer.',
    about: 'Business OS runs a real cosmetics shop in Cambodia. The same Cloudflare Worker serves the owner and cashier back office and the public storefront, and every screen works in English and Khmer.',
    features: [
      'Point of sale with barcode and camera scanning, held orders and shift controls',
      'Offline-first PWA: sales queue in IndexedDB and sync when the connection returns',
      'Shop and warehouse inventory with transfers, FIFO batches and stock-in sessions',
      'Sales hub with amendments, returns, fees, reports and exports',
      'Public storefront with brand rail, filters, promotions and a live-preview editor',
      'Thermal receipts and QR codes, real-time sync across devices, audit log with undo',
      'About 6,100 translated strings in both English and Khmer',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Cloudflare Workers', 'D1', 'R2', 'Durable Objects', 'Hono'],
    note: 'In production for Leang Beauty. The admin screenshots use the repository’s test fixtures, so product names are synthetic.',
    links: [
      { label: 'Visit storefront', href: 'https://leangbeauty.com', kind: 'live' },
      { label: 'Source', href: gh('business-os'), kind: 'code' },
    ],
    route: 'Retail POS + storefront, EN/KH', gate: 'CLOUDFLARE',
  },
  {
    id: 'learn', code: 'LRN', no: '02', name: 'LEARN', color: 'cyan', featured: true,
    cats: ['ai', 'software'], kicker: 'AI · EdTech', year: '2026',
    status: { label: 'Active development', color: 'cyan' },
    tagline: 'Capture → create → practise → review.',
    summary: 'Notes, docs, sheets and slides beside AI tutoring, quizzes, vocabulary practice and progress tracking.',
    about: 'A personal study studio. Material you write in the studio becomes practice: the AI tutor can coach, quiz, make flashcards or translate, and the practice modes track what you keep getting wrong.',
    features: [
      'Studio for notes, docs, sheets (CSV export) and slides (PPTX export)',
      'AI tutor modes: coach, rewrite, quiz, flashcards, translate and mistake review',
      'Practice: quizzes, timed sprints, flashcards, matching and review cards',
      'Study rooms, group chat with calls, and study battles over Durable Objects',
      'Knowledge vault, graph, calendar planner and a file library on R2',
      '18 interface languages, including Khmer, Chinese and Arabic (RTL)',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'TipTap', 'Cloudflare D1 · R2 · DO'],
    note: 'Features vary in readiness. The demo accounts are listed on the login page.',
    links: [
      { label: 'Open app', href: 'https://learn-ten-pearl.vercel.app', kind: 'live' },
      { label: 'Cloudflare mirror', href: 'https://learn.learn-app.workers.dev', kind: 'live' },
      { label: 'Source', href: gh('LEARN'), kind: 'code' },
    ],
    route: 'Notes → AI tutor → quizzes', gate: 'NEXT.JS',
  },
  {
    id: 'allchess', code: 'ACH', no: '03', name: 'AllChess', color: 'acid', featured: true,
    cats: ['games', 'software'], kicker: 'Games · Web', year: '2026', play: 'allchess',
    status: { label: 'Public · playable', color: 'acid' },
    tagline: 'Discover how the world plays chess.',
    summary: 'Classic chess and 20 playable variants, from Xiangqi and Shogi to Makruk and Janggi, with bots, rooms and rule guides.',
    about: 'Play first, learn as you go. AllChess has its own rules engine for chess-family games from around the world. Bots run in the browser: Stockfish 18 for classic chess and a custom search for every other variant.',
    features: [
      '20 playable games: Chess960, Crazyhouse, Xiangqi, Shogi, Janggi, Makruk, Chaturanga, draughts…',
      'Rule guides for 26 more, including Ouk Chaktrang (Khmer chess), Go and Hnefatafl',
      'Bots from 100 to 4000 Elo; Stockfish WASM for classic chess',
      'Quick match, bot, offline pass-and-play, friend rooms and spectating',
      'Move review, undo/redo and AI game analysis',
      '19 languages and 13 piece sets',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'Stockfish WASM', 'Cloudflare D1 · DO'],
    note: 'Sign-in is optional: guests can play every offline and bot mode.',
    links: [
      { label: 'Play live', href: 'https://allchess.learn-app.workers.dev', kind: 'live' },
      { label: 'Source', href: gh('AllChess'), kind: 'code' },
    ],
    route: 'Chess variants of the world', gate: 'NEXT + D1',
  },
  {
    id: 'urcut', code: 'URC', no: '04', name: 'UrCut + UrVoice', color: 'magenta', featured: true,
    cats: ['ai'], kicker: 'AI · Creative', year: '2026', private: true,
    status: { label: 'New · private', color: 'magenta' },
    tagline: 'Your cut. Visual, fast, private.',
    summary: 'A local-first, CapCut-style video editor with AI voiceovers and Khmer-aware captions from UrVoice, a speech engine on your own machine.',
    about: 'UrCut runs in the browser and keeps your media on your device: no account, no upload. UrVoice is its companion engine, an OpenAI-style speech API on localhost for transcription, 132 preset voices and consent-gated Khmer voice cloning.',
    features: [
      'Icon-first editor: media, voice, text, stickers, effects and captions panels',
      'Auto captions with in-browser Whisper, plus SRT/ASS import and Khmer line wrapping',
      'AI voiceover takes dropped at the playhead with instant captions',
      'Local Khmer, English and Chinese speech engine (UrVoice, Python/FastAPI)',
      'Exports MP4/WebM in the browser and marks AI voices in the file metadata',
      'Seven bundled fonts, six of them Khmer, so text works offline',
    ],
    stack: ['Next.js', 'TypeScript', 'Rust/WASM (wgpu)', 'Python', 'faster-whisper', 'ONNX'],
    note: 'Built on OpenCut classic (MIT): the compositor, effects and timeline core come from OpenCut. Private source.',
    credit: { label: 'OpenCut classic (MIT)', href: 'https://github.com/OpenCut-app/OpenCut' },
    links: [],
    route: 'Local-first video editor + voice', gate: 'NEXT + PY',
  },
  {
    id: 'codeage', code: 'CDA', no: '05', name: 'CodeAge', color: 'violet', featured: true,
    cats: ['ai'], kicker: 'AI · Dev tools', year: '2026', private: true,
    status: { label: 'Alpha · private', color: 'violet' },
    tagline: 'AI conversations beside your code.',
    summary: 'A Windows workbench with chat and code panels, editor, terminals and Git diffs, using local Ollama models or API providers.',
    about: 'A local-first workbench for agents, projects and history. Up to nine chat and terminal panels sit next to a Monaco editor, with approval modes that decide what an agent may do on your machine.',
    features: [
      'Adaptive grid of up to nine chat and real terminal panels',
      'Code view with Monaco editor, file tree and diffs',
      'Built-in agents: builder, reviewer, researcher, debugger and planner',
      'Access modes (ask, approve, full, read-only) with an approvals inbox',
      'Encrypted local store (AES-256-GCM) with backups',
      'Assistant with voice and a 3D presence; scheduled routines',
    ],
    stack: ['Electron', 'React 19', 'TypeScript', 'Express', 'SQLite', 'Monaco', 'xterm'],
    note: 'Windows local alpha (0.7.x). No public download yet.',
    links: [],
    route: 'AI workbench beside your code', gate: 'ELECTRON',
  },
  {
    id: 'edsync', code: 'EDS', no: '06', name: 'EdSync', color: 'blue', featured: true,
    cats: ['software', 'ai'], kicker: 'EdTech', year: '2026',
    status: { label: 'Preview', color: 'blue' },
    tagline: 'Connect classroom work across roles.',
    summary: 'Separate student, teacher and admin spaces for lessons, classes, assignments, gradebooks and progress.',
    about: 'EdSync is a role-based learning workspace. Teachers build lessons with an AI lesson creator and a canvas studio, students work through classes and practice, and admins run portals for organisations.',
    features: [
      'AI lesson creator: slide lessons with Socratic questions and an exit ticket',
      'Course studio on a Fabric.js canvas with PPTX export',
      'Ten practice modes, from quizzes and exams to sprints and mistake retry',
      'Teacher gradebook, grading, analytics, planner and discussions',
      'Organisation portals with join codes and an admin console',
      'Nine languages, light and dark themes, offline sync',
    ],
    stack: ['Next.js 16', 'React 19', 'TypeScript', 'Fabric.js', 'Cloudflare D1 · R2 · Vectorize'],
    note: 'Public preview; classroom content is still being built.',
    links: [
      { label: 'Open app', href: 'https://edsync-two.vercel.app', kind: 'live' },
      { label: 'Cloudflare mirror', href: 'https://edsync.learn-app.workers.dev', kind: 'live' },
      { label: 'Source', href: gh('EdSync'), kind: 'code' },
    ],
    route: 'Classes for students & teachers', gate: 'NEXT.JS',
  },
  {
    id: 'living-kingdom', code: 'LKG', no: '07', name: 'Living Kingdom', color: 'lime', game: true,
    cats: ['games'], kicker: 'Game · Unreal Engine 5', year: '2026', private: true, play: 'worlds-within',
    status: { label: 'Prototype', color: 'volt' },
    tagline: 'A sandbox kingdom RPG in the making.',
    summary: 'An Unreal Engine 5.8 C++ prototype: combat, chopping and carrying, a realm gate to a second area, a Founder with procedural animation, and saves.',
    about: 'You are a founder with a small, protected Origin Space that is meant to grow into a home, market or capital. The UE5 build has two maps, physics props, falling trees, navmesh enemies with telegraphed attacks, a warden fight and a collect–repair–recruit–build loop. Two browser companions let you explore the world here.',
    features: [
      'About 50 native C++ gameplay classes (combat, carry, choppable trees, journey economy)',
      'Procedural animation: lean, breathing, look-at, foot IK, hands on carried items',
      '24-hour day cycle driving sun, fog and lamps; shared wind for grass and lanterns',
      'Tab hub with map, satchel, Founder page and rebindable controls',
      'Versioned saves with migration, packaged Windows builds and automation tests',
      'Browser companions: “Worlds Within” (WebGL) and “The First Hearth” decisions lab',
    ],
    stack: ['Unreal Engine 5.8', 'C++', 'Blueprints', 'Blender', 'WebGL'],
    note: 'Built with AI agents under my direction. The concept image is AI-generated reference art, labelled as such.',
    links: [
      { label: 'Play Worlds Within', href: '#arcade/worlds-within', kind: 'play' },
      { label: 'Play The First Hearth', href: '#arcade/first-hearth', kind: 'play' },
    ],
    route: 'Fantasy world, UE5 prototype', gate: 'UE5 C++',
  },
  {
    id: 'sandline', code: 'SND', no: '08', name: 'Sandline', color: 'orange', game: true,
    cats: ['games'], kicker: 'Game · Unreal Engine 5', year: '2026', private: true, play: 'sandline',
    status: { label: 'Offline prototype', color: 'orange' },
    tagline: 'A tactical shooter against bots.',
    summary: 'A UE 5.8 shooter with 19 modes on six generated maps, bots with vision and reaction delay, a buy economy and a battle royale. Its first version plays in the browser.',
    about: 'Sandline started as a three.js arena (v1, playable here) and moved to Unreal Engine 5. The UE build is played offline against bots; online multiplayer is not built yet.',
    features: [
      '19 modes: competitive defusal, wingman, deathmatch, arcade modes, war and a battle royale',
      'Six maps designed in Python and built at runtime, from Sirocco to a 128×128 island',
      'Bots with a vision cone, line of sight, reaction delay, aim drift and A* navigation',
      'Buy menu and money economy, bomb plant/defuse, storm and airdrops',
      'Blender-generated agents, guns and props; Python-synthesised audio',
      'Headless test runs: every mode on every map, with logged kills',
    ],
    stack: ['Unreal Engine 5.8', 'C++', 'Blueprints', 'Python', 'Blender', 'three.js (v1)'],
    note: 'Built with AI agents under my direction. v1 web build is a historical prototype.',
    links: [{ label: 'Play the web arena', href: '#arcade/sandline', kind: 'play' }],
    route: 'Offline bot shooter, UE5', gate: 'UE5 C++',
  },
  {
    id: 'wreckabulary', code: 'WRK', no: '09', name: 'Wreckabulary', color: 'violet', game: true,
    cats: ['games', 'team'], kicker: 'Game · Team · COMP4122', year: '2026',
    status: { label: 'Team project', color: 'violet' },
    tagline: 'Wreck the room, build the word!',
    summary: 'A 2–4 player couch party game in Unity 6: smash furniture into its letters, then spell weapons, walls and wings.',
    about: 'Everything is made of letter tiles. Smash → scavenge → spell → summon: carry up to six letters, open the word wheel and summon a SHIELD, SPRING or a swarm of BEES. Versus, co-op “Moving Day” and a tutorial are in; the art is still placeholder blocks.',
    features: [
      'Destruction that bursts objects into the exact letters of their name',
      'Real-time word solver over the letters you carry',
      'Drop-in joining for up to four gamepads or two players on one keyboard',
      'Versus “Dibs!” (letters are your health) and co-op “Moving Day”',
      'Ragdoll roommates with a wobbly rig; pooled physics letter tiles',
    ],
    stack: ['Unity 6', 'C#', 'URP', 'Input System'],
    note: 'Key art and the gameplay image are the team’s concept mock-ups; in-game art is still placeholder.',
    links: [
      { label: 'Source', href: gh('wreckabulary'), kind: 'code' },
      { label: 'Team repo', href: 'https://github.com/cchayadap/wreckabulary', kind: 'code' },
    ],
  },
  {
    id: 'omnidrama', code: 'OMD', no: '10', name: 'OmniDrama', color: 'blue',
    cats: ['software'], kicker: 'Media · Local app', year: '2026', private: true,
    status: { label: 'New · private', color: 'orange' },
    tagline: 'Your shows in one local library.',
    summary: 'A Windows video library: searchable catalogue, episode player with saved progress, and a studio that converts uploads with FFmpeg.',
    about: 'A local library for one administrator: import episodes, and FFmpeg validates and converts them for the browser player. Publishing waits until rights are declared and every episode is present.',
    features: [
      'Discover page with featured series, genres and production-type filters',
      'Episode browser with filters, six sort orders and watch state',
      'Player with seeking, speed, auto-next, saved position and shortcuts',
      'Durable import jobs with FFmpeg transcoding and posters',
      'Scheduled feed scans that respect robots.txt, plus a review inbox',
      'Strict CSP, same-origin and SSRF guards; runs only on localhost',
    ],
    stack: ['React 19', 'TypeScript', 'Express 5', 'SQLite', 'FFmpeg', 'Vite'],
    note: 'Ships with an original sample series only; not a public streaming service.',
    links: [],
    route: 'Local video library + player', gate: 'NODE + TS',
  },
  {
    id: 'khshop', code: 'KHS', no: '11', name: 'KhShop', color: 'magenta',
    cats: ['software'], kicker: 'Marketplace pilot', year: '2026', private: true,
    status: { label: 'Pilot · test data', color: 'magenta' },
    tagline: 'Shopping designed around Khmer.',
    summary: 'A Khmer-first marketplace pilot: local discovery, USD/KHR prices, offers and viewing appointments.',
    about: 'Khmer by default with an English switch, prices in both US dollars and riel, and search that understands Khmer text. The pilot uses fictional shops; orders don’t take payment.',
    features: [
      'Khmer-aware search normalisation with multi-term ranking',
      'USD/KHR display from a live rate with a fallback',
      'Offers, viewing appointments and order state machines',
      'Roles from buyer to owner, with moderation and report thresholds',
      'Credit ledger guarded by SQLite triggers',
      'On-device visual search experiment (CLIP in a Web Worker)',
    ],
    stack: ['React 19', 'Vite', 'TypeScript', 'Drizzle', 'Cloudflare D1'],
    note: 'Owner-only pilot being rebuilt; sample shops are fictional.',
    links: [],
  },
  {
    id: 'jarvis', code: 'JRV', no: '12', name: 'Secretary Jarvis', color: 'cyan',
    cats: ['ai'], kicker: 'AI · Desktop', year: '2026',
    status: { label: 'Prototype', color: 'cyan' },
    tagline: 'A desktop home for an AI assistant.',
    summary: 'An Electron shell around a Python backend: chat, voice, a terminal, local-model control and live stats on one home screen.',
    about: 'Jarvis wraps an agent in a desktop app: a 3D orb, assistant stream, terminal and voice on one screen, with local runtimes (llama.cpp, vLLM, Ollama) and swappable “souls”.',
    features: [
      'Home screen with 3D orb, assistant stream, terminal and live stats',
      'Local model runtimes with priority fallback, or API providers',
      'Voice in and out: Kokoro TTS, faster-whisper or whisper.cpp',
      'Hot-swappable identity and voice profiles',
      'Skills hub, plugins, MCP and a cron scheduler',
      'Seven themes and 16 interface languages',
    ],
    stack: ['Electron', 'React 19', 'TypeScript', 'Python', 'FastAPI', 'three.js'],
    note: 'Built on the open-source Hermes Agent by Nous Research (MIT).',
    credit: { label: 'Hermes Agent by Nous Research (MIT)', href: 'https://github.com/NousResearch/hermes-agent' },
    links: [{ label: 'Source', href: gh('Secretary-Jarvis'), kind: 'code' }],
  },
  {
    id: 'cargo-twin', code: 'CCT', no: '13', name: 'Cathay Cargo Twin', color: 'acid',
    cats: ['team', 'software'], kicker: 'Hackathon · Team · Nov 2025', year: '2025', play: 'cargo-twin',
    status: { label: 'Playable prototype', color: 'acid' },
    tagline: 'Planning air cargo in 3D.',
    summary: 'AInnovator hackathon prototype: add packages with temperature and fragility needs, pack them into ULD containers, then load the containers into a freighter hold.',
    about: 'Built for the Cathay AInnovator hackathon. A 3D bin-packing heuristic stacks packages with support, fragility and temperature rules, and a second view places the finished ULDs in a freighter hold while tracking centre of gravity.',
    features: [
      'Seven packing strategies, from max weight to fragile-first',
      'Stacking rules: 70% support, fragile on top, heavy low, temperature separation',
      'AKE, AKN, AKH and custom ULDs; B747-8F, B777F, A350F and more',
      'Hold optimiser with centre-of-gravity and stability checks',
      'Hand-written 3D projection on canvas: drag to rotate, scroll to zoom',
    ],
    stack: ['React', 'TypeScript', 'Vite', 'Tailwind', 'Canvas 2D'],
    note: 'Team prototype, designed in Figma Make. Deterministic heuristics, no ML.',
    links: [
      { label: 'Play here', href: '#arcade/cargo-twin', kind: 'play' },
      { label: 'Original site', href: 'https://ainnovator-cathay-cargotwin.figma.site', kind: 'live' },
      { label: 'Source', href: gh('Ainnovator_Prototype'), kind: 'code' },
    ],
  },
  {
    id: 'ai-summary', code: 'AIS', no: '14', name: 'AI Summary', color: 'orange',
    cats: ['ai'], kicker: 'AI · Earlier project', year: '2026',
    status: { label: 'Earlier project', color: 'orange' },
    tagline: 'Ask questions of your documents.',
    summary: 'Summaries and Q&A for PDF, Word, slides and text files, with projects, history and chat on Supabase.',
    about: 'A course project that became my first full AI app: text is extracted in the browser, summarised by a model of your choice through OpenRouter, and saved with a chat history per document.',
    features: [
      'In-browser text extraction for PDF, DOCX, PPTX and TXT',
      'Six selectable models through OpenRouter',
      'Document chat with saved history and suggested follow-up questions',
      'Supabase auth (email, Google, magic link), storage and projects',
      'Readability settings and dark mode',
    ],
    stack: ['React', 'Vite', 'Supabase', 'pdf.js', 'OpenRouter'],
    note: 'Its hosted version is offline; the source is public.',
    links: [{ label: 'Source', href: gh('ai-summary-app'), kind: 'code' }],
  },
];

export const COURSE = [
  { name: 'Secure instant messaging', what: 'COMP3334 group project: messaging with end-to-end encryption', href: gh('Comp3334_G22_Secure-Instant-Messaging-with-End-to-End-Encryption') },
  { name: 'Information systems development', what: 'COMP3122 group project', href: gh('Comp3122_G13_Information-Systems-Development') },
  { name: 'COMP2021 project', what: 'Group course project (fork of the team repository)', href: gh('COMP2021Project') },
  { name: 'Operating systems', what: 'COMP2432 group project in C (private repository)' },
];

// Arcade cabinets: `src` is self-hosted under play/, `live` is an external embed.
export const ARCADE = [
  {
    id: 'sandline', project: 'sandline', title: 'Sandline · Web Arena', kind: 'FPS · three.js',
    blurb: 'Ten operators, one container yard. Team deathmatch, free-for-all, domination or gun game against bots.',
    controls: 'WASD move · mouse look · click fire · R reload · 1–4 weapons · Esc release mouse',
    src: 'play/sandline/index.html', aspect: '16 / 9', desktop: true,
  },
  {
    id: 'worlds-within', project: 'living-kingdom', title: 'Living Kingdom · Worlds Within', kind: 'Explore · WebGL',
    blurb: 'Zoom from Earth into the inner realms and down to Jadewater valley, then walk it: gather three qi crystals and open the Origin Gate.',
    controls: 'Drag to orbit · scroll to zoom · in the valley: Walk here, WASD, E to interact',
    src: 'play/worlds-within/index.html', aspect: '16 / 9', size: '17 MB',
  },
  {
    id: 'first-hearth', project: 'living-kingdom', title: 'Living Kingdom · The First Hearth', kind: 'Strategy · decisions',
    blurb: 'A mechanics lab for the kingdom: 18 decisions about who to trust and how to prepare your region before the tide arrives.',
    controls: 'Click to choose · progress saves in your browser', cover: 'The First Hearth',
    src: 'play/first-hearth/index.html', aspect: '16 / 10',
  },
  {
    id: 'cargo-twin', project: 'cargo-twin', title: 'Cathay Cargo Twin', kind: 'Sim · 3D packing',
    blurb: 'Create a ULD, add packages, pick a strategy and watch them stack. Then load the finished ULDs into a freighter.',
    controls: 'Drag to rotate · scroll to zoom · best on a wide screen',
    src: 'play/cargo-twin/index.html', aspect: '16 / 10', desktop: true,
  },
  {
    id: 'allchess', project: 'allchess', title: 'AllChess · vs bot', kind: 'Board · live app',
    blurb: 'The live AllChess app, embedded: play a bot, or pick Xiangqi, Shogi or any of 20 games from the menu.',
    controls: 'Click or drag pieces · runs on Cloudflare', cover: 'Classic chess',
    live: 'https://allchess.learn-app.workers.dev/en/play/classic?bot=normal&mode=bot&time=rapid', aspect: '16 / 10',
  },
];

export const FLIGHTS = ['business-os', 'learn', 'urcut', 'codeage', 'allchess', 'edsync', 'living-kingdom', 'sandline', 'omnidrama'];

export const TOOLBOX = [
  { title: 'Languages', color: 'cyan', items: ['TypeScript', 'JavaScript', 'Python', 'C++', 'C', 'Java', 'SQL', 'C#'] },
  { title: 'Frontend & apps', color: 'magenta', items: ['React', 'Next.js', 'Vite', 'Electron', 'Tailwind', 'TipTap', 'three.js', 'PWA'] },
  { title: 'Cloud & data', color: 'volt', items: ['Cloudflare Workers', 'D1', 'R2', 'Durable Objects', 'Hono', 'Supabase', 'SQLite', 'Express'] },
  { title: 'AI', color: 'violet', items: ['Claude', 'Codex', 'Ollama', 'Whisper', 'Local TTS', 'OpenRouter', 'AI provider APIs'] },
  { title: 'Games', color: 'acid', items: ['Unreal Engine 5', 'Blueprints', 'Unity 6', 'Blender', 'WebGL'] },
  { title: 'Also used', color: 'orange', items: ['Docker', 'PostgreSQL', 'Redis', 'DuckDB', 'Vercel', 'Git', 'pnpm', 'Bun', 'Playwright'] },
];

// which projects use a tool (for the toolbox cross-links)
export const TOOL_USES = {
  TypeScript: ['business-os', 'learn', 'allchess', 'urcut', 'codeage', 'edsync', 'omnidrama', 'khshop', 'jarvis', 'cargo-twin'],
  JavaScript: ['ai-summary', 'sandline'],
  Python: ['urcut', 'jarvis', 'sandline'],
  'C++': ['living-kingdom', 'sandline'],
  'C#': ['wreckabulary'],
  React: ['business-os', 'learn', 'allchess', 'urcut', 'codeage', 'edsync', 'omnidrama', 'khshop', 'jarvis', 'cargo-twin', 'ai-summary'],
  'Next.js': ['learn', 'allchess', 'urcut', 'edsync'],
  Vite: ['business-os', 'codeage', 'omnidrama', 'khshop', 'cargo-twin', 'ai-summary'],
  Electron: ['codeage', 'jarvis'],
  TipTap: ['learn', 'edsync'],
  Tailwind: ['learn', 'edsync', 'allchess', 'urcut', 'khshop', 'cargo-twin', 'business-os'],
  'three.js': ['sandline', 'jarvis', 'codeage'],
  PWA: ['business-os', 'edsync', 'khshop'],
  'Cloudflare Workers': ['business-os', 'learn', 'allchess', 'edsync', 'khshop'],
  D1: ['business-os', 'learn', 'allchess', 'edsync', 'khshop'],
  R2: ['business-os', 'learn', 'edsync'],
  'Durable Objects': ['business-os', 'learn', 'allchess'],
  Hono: ['business-os'],
  Supabase: ['ai-summary'],
  SQLite: ['codeage', 'omnidrama', 'khshop'],
  Express: ['codeage', 'omnidrama'],
  Whisper: ['urcut', 'jarvis'],
  'Local TTS': ['urcut', 'jarvis'],
  Ollama: ['codeage', 'jarvis'],
  OpenRouter: ['ai-summary'],
  'Unreal Engine 5': ['living-kingdom', 'sandline'],
  Blueprints: ['living-kingdom', 'sandline'],
  'Unity 6': ['wreckabulary'],
  Blender: ['living-kingdom', 'sandline'],
  WebGL: ['living-kingdom', 'sandline'],
  Playwright: ['business-os', 'allchess'],
};

export const MILESTONES = [
  { date: 'FEB 2023', title: 'Monash University', sub: 'CS study · Australia', color: 'blue' },
  { date: 'JUL 2023', title: 'Joined GitHub', sub: 'hello, world', color: 'dim' },
  { date: '2024', title: 'PolyU · Hong Kong', sub: 'Computer Science', color: 'cyan' },
  { date: 'MAR 2025', title: 'Operating Systems', sub: 'group project in C', color: 'violet' },
  { date: 'AUG 2025', title: 'Student Assistant', sub: 'PolyU · Aug–Oct 2025', color: 'acid' },
  { date: 'NOV 2025', title: 'AInnovator hackathon', sub: 'Cathay Cargo Twin (team)', color: 'magenta' },
  { date: 'FEB 2026', title: 'AI Summary', sub: 'document Q&A app', color: 'orange' },
  { date: 'MAR 2026', title: 'Business OS', sub: 'retail POS begins', color: 'volt' },
  { date: 'MAY 2026', title: 'LEARN · AllChess', sub: 'EdSync · Jarvis', color: 'cyan' },
  { date: 'SEP 2026', title: 'CodeAge · UrCut', sub: 'UE5 prototypes · Wreckabulary', color: 'magenta', now: true },
  { date: 'JUL 2027', title: 'Graduation', sub: 'expected', color: 'acid', future: true },
];
