// Generated by tools/images.py: screenshots per project.
export const SHOTS = {
 "business-os": [
  {
   "src": "img/shots/business-os/01.webp",
   "sm": "img/shots/business-os/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Point of sale: three lines in the cart, totals in USD and riel (test fixture data).",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/02.webp",
   "sm": "img/shots/business-os/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "The same till in Khmer, from the app's language switch.",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/03.webp",
   "sm": "img/shots/business-os/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Customer storefront, About tab.",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/04.webp",
   "sm": "img/shots/business-os/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Storefront editor with live preview (test fixture data).",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/05.webp",
   "sm": "img/shots/business-os/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Products with cost, price, margin and stock.",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/06.webp",
   "sm": "img/shots/business-os/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Receipt settings beside a live 80 mm receipt preview.",
   "kind": "screen"
  },
  {
   "src": "img/shots/business-os/07.webp",
   "sm": "img/shots/business-os/07-sm.webp",
   "w": 900,
   "h": 315,
   "caption": "The live Leang Beauty storefront, September 2026.",
   "kind": "wide"
  },
  {
   "src": "img/shots/business-os/08.webp",
   "sm": "img/shots/business-os/08-sm.webp",
   "w": 780,
   "h": 1688,
   "caption": "Storefront on a phone.",
   "kind": "phone"
  }
 ],
 "learn": [
  {
   "src": "img/shots/learn/01.webp",
   "sm": "img/shots/learn/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Landing page: capture what you learn, turn it into practice.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/02.webp",
   "sm": "img/shots/learn/02-sm.webp",
   "w": 1600,
   "h": 1000,
   "caption": "Studio: projects, templates and recent work.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/03.webp",
   "sm": "img/shots/learn/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Algorithms practice quiz, two of six answered (demo account).",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/04.webp",
   "sm": "img/shots/learn/04-sm.webp",
   "w": 1600,
   "h": 1000,
   "caption": "Dashboard with AI suggestions, review queue and calendar.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/05.webp",
   "sm": "img/shots/learn/05-sm.webp",
   "w": 1600,
   "h": 1000,
   "caption": "AI tutor workspace.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/06.webp",
   "sm": "img/shots/learn/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Studio with the demo account's seeded notes.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/07.webp",
   "sm": "img/shots/learn/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Product tour: the dashboard slide.",
   "kind": "screen"
  },
  {
   "src": "img/shots/learn/08.webp",
   "sm": "img/shots/learn/08-sm.webp",
   "w": 780,
   "h": 1688,
   "caption": "Sign-in on a phone, with demo-account shortcuts.",
   "kind": "phone"
  }
 ],
 "allchess": [
  {
   "src": "img/shots/allchess/01.webp",
   "sm": "img/shots/allchess/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Classic chess in the 29 September arcade build: bot replies and a played suggestion on the 3D tabletop.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/shore-desktop.webp",
   "sm": "img/shots/allchess/shore-desktop-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Shore Konane in the latest 29 September arcade: stone board and counters under studio lighting.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/02.webp",
   "sm": "img/shots/allchess/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Xiangqi with the Celadon collection: glazed ceramic discs on a wood 3D board.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/03.webp",
   "sm": "img/shots/allchess/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Shogi with the carved collection, lacquered glyphs and hand stands.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/04.webp",
   "sm": "img/shots/allchess/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Ouk Chaktrang (Khmer chess) with the Courtyard sandstone and charcoal set.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/05.webp",
   "sm": "img/shots/allchess/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Game studio home: a visual library with bot, local, friend, quick match and watch modes.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/06.webp",
   "sm": "img/shots/allchess/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "English draughts with the Club ivory and oxblood counters.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/07.webp",
   "sm": "img/shots/allchess/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Board style picker: piece collection, 2D style and board colours per game.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/08.webp",
   "sm": "img/shots/allchess/08-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "All 21 games, each with its own artwork.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/09.webp",
   "sm": "img/shots/allchess/09-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Move review with factual notation and playback.",
   "kind": "screen"
  },
  {
   "src": "img/shots/allchess/10.webp",
   "sm": "img/shots/allchess/10-sm.webp",
   "w": 780,
   "h": 1688,
   "caption": "Celadon Xiangqi on a phone.",
   "kind": "phone"
  }
 ],
 "urcut": [
  {
   "src": "img/shots/urcut/01.webp",
   "sm": "img/shots/urcut/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Khmer and Chinese text on a 9:16 video, both clips on the timeline.",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/02.webp",
   "sm": "img/shots/urcut/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "AI voice panel with a Khmer script (voice list mocked here; UrVoice runs on your machine).",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/03.webp",
   "sm": "img/shots/urcut/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Imported English and Khmer captions on the timeline (sample subtitle file).",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/04.webp",
   "sm": "img/shots/urcut/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Editor: media, preview, transform properties and timeline.",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/05.webp",
   "sm": "img/shots/urcut/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Chinese voice gallery (mocked voice list).",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/06.webp",
   "sm": "img/shots/urcut/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Projects dashboard with aspect-ratio tiles.",
   "kind": "screen"
  },
  {
   "src": "img/shots/urcut/07.webp",
   "sm": "img/shots/urcut/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "A 9:16 poster project in the light theme.",
   "kind": "screen"
  }
 ],
 "codeage": [
  {
   "src": "img/shots/codeage/01.webp",
   "sm": "img/shots/codeage/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Chat panels beside a real terminal (no model connected, drafts only).",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/02.webp",
   "sm": "img/shots/codeage/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Code view: file tree, editor and terminal.",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/03.webp",
   "sm": "img/shots/codeage/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Built-in agents: builder, code reviewer, researcher, debugger, planner.",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/04.webp",
   "sm": "img/shots/codeage/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Jarvis, the voice assistant, with its 3D presence.",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/05.webp",
   "sm": "img/shots/codeage/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Connect a model: Ollama, OpenAI-compatible or Anthropic.",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/06.webp",
   "sm": "img/shots/codeage/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Library of imported project assets.",
   "kind": "screen"
  },
  {
   "src": "img/shots/codeage/07.webp",
   "sm": "img/shots/codeage/07-sm.webp",
   "w": 900,
   "h": 315,
   "caption": "Chat and side panel, September 2026 capture.",
   "kind": "wide"
  }
 ],
 "edsync": [
  {
   "src": "img/shots/edsync/01.webp",
   "sm": "img/shots/edsync/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Teacher: create a lesson with AI, from a draft or blank.",
   "kind": "screen"
  },
  {
   "src": "img/shots/edsync/02.webp",
   "sm": "img/shots/edsync/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Admin command center.",
   "kind": "screen"
  },
  {
   "src": "img/shots/edsync/03.webp",
   "sm": "img/shots/edsync/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Student home.",
   "kind": "screen"
  },
  {
   "src": "img/shots/edsync/04.webp",
   "sm": "img/shots/edsync/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Organisation sign-in.",
   "kind": "screen"
  },
  {
   "src": "img/shots/edsync/05.webp",
   "sm": "img/shots/edsync/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Student home, light theme.",
   "kind": "screen"
  },
  {
   "src": "img/shots/edsync/06.webp",
   "sm": "img/shots/edsync/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Teacher work builder.",
   "kind": "screen"
  }
 ],
 "living-kingdom": [
  {
   "src": "img/shots/living-kingdom/01.webp",
   "sm": "img/shots/living-kingdom/01-sm.webp",
   "w": 900,
   "h": 315,
   "caption": "Unreal Engine 5 (the reference build): the Founder at the Origin shrine.",
   "kind": "wide"
  },
  {
   "src": "img/shots/living-kingdom/02.webp",
   "sm": "img/shots/living-kingdom/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "The Origin at golden hour, browser edition: sun and fog from the UE time-of-day keys, with the objective tracker, minimap and vitals.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/03.webp",
   "sm": "img/shots/living-kingdom/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Stonebrook, the second map: the village pump you repair, kit-built houses and the villagers Tobin and Elias.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/04.webp",
   "sm": "img/shots/living-kingdom/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Veil shades in the outer meadow, locked on mid-swing; the warden waits up the slope.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/05.webp",
   "sm": "img/shots/living-kingdom/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Felling a jacaranda: three swings, then it splits into logs you can carry.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/06.webp",
   "sm": "img/shots/living-kingdom/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Carrying a log to the stash; each one stowed adds timber to the journey ledger.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/07.webp",
   "sm": "img/shots/living-kingdom/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "The Tab hub: ten sections, live journey data, the local map and the current quest.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/08.webp",
   "sm": "img/shots/living-kingdom/08-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Founder page: a live turntable with coat and hair dyes, vitals and the journal.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/09.webp",
   "sm": "img/shots/living-kingdom/09-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Title screen over the floating Origin at dusk.",
   "kind": "screen"
  },
  {
   "src": "img/shots/living-kingdom/10.webp",
   "sm": "img/shots/living-kingdom/10-sm.webp",
   "w": 700,
   "h": 1000,
   "caption": "Founder character render.",
   "kind": "render"
  }
 ],
 "sandline": [
  {
   "src": "img/shots/sandline/01.webp",
   "sm": "img/shots/sandline/01-sm.webp",
   "w": 900,
   "h": 315,
   "caption": "Unreal Engine 5 (the reference build): Sirocco, buy phase.",
   "kind": "wide"
  },
  {
   "src": "img/shots/sandline/02.webp",
   "sm": "img/shots/sandline/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Firefight on Sirocco, browser edition: first-person arms with IK, muzzle flash, hit marker, radar and kill feed.",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/03.webp",
   "sm": "img/shots/sandline/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Old Town at golden hour in Domination, with the A/B/C capture points on the HUD and radar.",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/04.webp",
   "sm": "img/shots/sandline/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Buy menu: the full arsenal priced from the UE weapon table, with a stat card for the hovered gun.",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/05.webp",
   "sm": "img/shots/sandline/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Play screen: mode families, the maps for the chosen mode and match options (bots, skill, side, match length).",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/06.webp",
   "sm": "img/shots/sandline/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Agent select: the five Blender-built agents, chosen per side.",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/07.webp",
   "sm": "img/shots/sandline/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Match summary: 7:3 win, leaderboard, MVP and XP rewards carried into the career profile.",
   "kind": "screen"
  },
  {
   "src": "img/shots/sandline/08.webp",
   "sm": "img/shots/sandline/08-sm.webp",
   "w": 1024,
   "h": 1024,
   "caption": "Battle royale island, generated in Python.",
   "kind": "render"
  }
 ],
 "wreckabulary": [
  {
   "src": "img/shots/wreckabulary/01.webp",
   "sm": "img/shots/wreckabulary/01-sm.webp",
   "w": 1600,
   "h": 900,
   "caption": "Key art (team concept).",
   "kind": "screen"
  },
  {
   "src": "img/shots/wreckabulary/02.webp",
   "sm": "img/shots/wreckabulary/02-sm.webp",
   "w": 1600,
   "h": 900,
   "caption": "Gameplay mock-up: versus round (team concept).",
   "kind": "screen"
  },
  {
   "src": "img/shots/wreckabulary/03.webp",
   "sm": "img/shots/wreckabulary/03-sm.webp",
   "w": 1600,
   "h": 1600,
   "caption": "Early room sketch.",
   "kind": "art"
  },
  {
   "src": "img/shots/wreckabulary/04.webp",
   "sm": "img/shots/wreckabulary/04-sm.webp",
   "w": 1600,
   "h": 1600,
   "caption": "Logo sketch.",
   "kind": "art"
  }
 ],
 "omnidrama": [
  {
   "src": "img/shots/omnidrama/01.webp",
   "sm": "img/shots/omnidrama/01-sm.webp",
   "w": 1280,
   "h": 900,
   "caption": "Discover: featured series and your collection.",
   "kind": "screen"
  },
  {
   "src": "img/shots/omnidrama/02.webp",
   "sm": "img/shots/omnidrama/02-sm.webp",
   "w": 1366,
   "h": 900,
   "caption": "Episodes with filters and watch state.",
   "kind": "screen"
  },
  {
   "src": "img/shots/omnidrama/03.webp",
   "sm": "img/shots/omnidrama/03-sm.webp",
   "w": 390,
   "h": 844,
   "caption": "Episodes on a phone.",
   "kind": "phone"
  }
 ],
 "khshop": [
  {
   "src": "img/shots/khshop/01.webp",
   "sm": "img/shots/khshop/01-sm.webp",
   "w": 900,
   "h": 315,
   "caption": "Home with sample listings, September 2026 capture (fictional shops).",
   "kind": "wide"
  },
  {
   "src": "img/shots/khshop/02.webp",
   "sm": "img/shots/khshop/02-sm.webp",
   "w": 300,
   "h": 300,
   "caption": "A sample listing card.",
   "kind": "art"
  }
 ],
 "jarvis": [
  {
   "src": "img/shots/jarvis/01.webp",
   "sm": "img/shots/jarvis/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Home in the cyberpunk theme: orb, live stats and terminal.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/02.webp",
   "sm": "img/shots/jarvis/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Home in the default theme.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/03.webp",
   "sm": "img/shots/jarvis/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Models: local runtimes and model settings.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/04.webp",
   "sm": "img/shots/jarvis/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Souls: swappable identity and voice profiles.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/05.webp",
   "sm": "img/shots/jarvis/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Skills hub.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/06.webp",
   "sm": "img/shots/jarvis/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Settings with theme presets.",
   "kind": "screen"
  },
  {
   "src": "img/shots/jarvis/07.webp",
   "sm": "img/shots/jarvis/07-sm.webp",
   "w": 1024,
   "h": 1024,
   "caption": "App icon.",
   "kind": "art"
  }
 ],
 "cargo-twin": [
  {
   "src": "img/shots/cargo-twin/studio-v3-desktop.webp",
   "sm": "img/shots/cargo-twin/studio-v3-desktop-sm.webp",
   "w": 1440,
   "h": 1356,
   "caption": "Cargo Twin v3: a 40-piece mixed delivery load with calculated usable-space and payload percentages, handling rules and replayable 3D placements.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/studio-v3-mobile.webp",
   "sm": "img/shots/cargo-twin/studio-v3-mobile-sm.webp",
   "w": 390,
   "h": 2721,
   "caption": "Cargo Twin v3 on a phone: editable cargo and custom transport spaces with the same local packing engine.",
   "kind": "phone"
  },
  {
   "src": "img/shots/cargo-twin/01.webp",
   "sm": "img/shots/cargo-twin/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "A 96-in PMC pallet packed from seven air waybills, with dangerous-goods labels and the ULD's centre of gravity.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/02.webp",
   "sm": "img/shots/cargo-twin/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Physics stress test: cartons that tipped or shifted are flagged and the ULD is marked for restacking.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/03.webp",
   "sm": "img/shots/cargo-twin/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "777F load plan after auto-optimisation: 32 ULDs, deck plan and the CG envelope (representative data).",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/04.webp",
   "sm": "img/shots/cargo-twin/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Strategy comparison on a 589-piece manifest: the genetic refinement wins with 36 ULDs.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/05.webp",
   "sm": "img/shots/cargo-twin/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Stress test running: loose cartons lean into the void under a 1.5 g lateral load.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/06.webp",
   "sm": "img/shots/cargo-twin/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Equipment library: ULD contours drawn to scale with weights and aircraft compatibility.",
   "kind": "screen"
  },
  {
   "src": "img/shots/cargo-twin/07.webp",
   "sm": "img/shots/cargo-twin/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Version 1 (hackathon, Nov 2025): the original pseudo-3D packing view.",
   "kind": "screen"
  }
 ],
 "ai-summary": [
  {
   "src": "img/shots/ai-summary/01.webp",
   "sm": "img/shots/ai-summary/01-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "One click on a sample: TL;DR, key phrases and a suggested question answered with page citations, the source highlighted.",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/02.webp",
   "sm": "img/shots/ai-summary/02-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Home: no account, no server, your files stay in the browser.",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/03.webp",
   "sm": "img/shots/ai-summary/03-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Local Q&A in dark mode: cited sentences, and a plain answer when the text can't say.",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/04.webp",
   "sm": "img/shots/ai-summary/04-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Study mode: a quiz generated from the document, with a citation for each answer.",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/05.webp",
   "sm": "img/shots/ai-summary/05-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Mind map from section headings and each section's key phrases.",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/06.webp",
   "sm": "img/shots/ai-summary/06-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Optional Claude mode: a streamed summary with citations (mocked response for this screenshot).",
   "kind": "screen"
  },
  {
   "src": "img/shots/ai-summary/07.webp",
   "sm": "img/shots/ai-summary/07-sm.webp",
   "w": 1440,
   "h": 900,
   "caption": "Version 1 (Feb 2026): Supabase sign-in.",
   "kind": "screen"
  }
 ]
};
